[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synthesizer"
version = "0.1.0"
description = "An additive synthesizer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "pygame>=2.6.1",
    "pyopengl>=3.1.10",
]

[project.scripts]
synthesizer = "additive_synthesizer.main:main"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
instrument_cluster = ["assets/**/*", "db/settings.json"]
